### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by taubenangriff** [Anno-Mods-by-EDGE/EDGE_Anno_1800_Mods#4]
Hello there,

First of all thanks for the PR on spice it up! Visiting your profile though greeted me with some semi-fun stuff... I was looking for a contact email or sth but I haven't found any so far, so I am just gonna post this as an issue here.

I have nothing against people using my mods as a base for theirs, or use code snippets from them. Also, I am always for more people jumping on the modding train. And what you do with them on your machine - don't care the slightest. 

What I don't really like are published 1:1 copies - and it seems that [Improved Arctic Heaters](https://github.com/Anno-Mods-by-EDGE/EDGE_Anno_1800_Mods/blob/EDGE_Repo/%5BGameplay%5D%20EDGE_ImprovedArcticHeaters/data/config/export/main/asset/assets.xml) is a more or less a 1:1 copy of the Spice it Up Gas Heater mod, the only things changed being icons and copyright. 

To quote from the repository readme: 
> All content made by EDGE is property of EDGE Gaming, but you are free to use it as you like provided you use Credits in your files, pointing to the original creator.

I would simply like you to respect that my code is my property, that's all. Please don't get this wrong - I ain't mad, but also want to bring this up. The reason I am not permitting straight copies (even with copyright notice to the original creator) is that I am the one who will get tons of messages if duplicates I don't manage aren't updated.

Wish you all the best to get started, and welcome to the Anno Modding community. 

Kind regards, Taubenangriff

**Comment by Lillemats90** [comment]
hello, tank you for the kind words about our start up with mods in Anno, and we are happy to have your repo forket to ours as its so much great content on there, and we use alot of the mods you have created in our regular games too.
im happy to see the passion that ppl have in the anno mod community.

i would like to point out that as we state in our about section none of the files in this repo have been made game ready, and is not  intended to be downloaded for play:

> About
>A collection of all our current and upcoming mods, keep in mind that most of the files on this repository have not been made game ready, so find your release on nexusmods.com/anno1800

and the only one on here that we have released for now is the mod adding white flags to trade ships, i can assure you it was never our intent to release a version that is a copy of your mod :) .

our intention has never been to release a version of this mod and its just a folder we have created changing the range and the quantity used by it for our own gamepaly, the folder have now been removed from the repo, and if we ever plan on releaseing anything based on your code or anyone elses this will be descussed with you or the original creator before anything is done.

as you can probably see this repo and the information on it have very recently been created, and we are still working on hashing out these kinds of things, so thank you very much for your feedback on this,
we will update our readme to make this info easier for our visitors to see, so that the info is not only in the about section, and i will close this issue, and hope that this settles your worries a little, we are also updating the site with easier access to our contact email, if you have anything else you'd like to talk about, questions, tips or tricks or anything like that  im very happy to get that on email: Mats@edgegaming.no have a great day :D
